[package]
name = "has_flag"
version = "0.1.0"
authors = ["suzh <20077871+SuZHui@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html